apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app:11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app:11
  template:
    metadata:
      labels:
        app: flask-app:11
    spec:
      containers:
      - name: flask-app:11
        image: asa96/flask-app:
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app:11
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: flask-app:11
